theme: jekyll-theme-slate
title: Edgar Martinez - Fullstack Developer
description: +3 years experienced engineer in multiple technologies.  Currently working at Gray Wolf developing software for e-commerce and content management system platforms, and other enterprise platforms.
